"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, XCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { billingApi, type BillingTransactionRecord } from "@/lib/billing/api";

export function TransactionDetailsPage({ transactionUuid }: { transactionUuid: string }) {
  const router = useRouter(); const [record, setRecord] = useState<BillingTransactionRecord | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { void billingApi.transaction(transactionUuid).then(setRecord).finally(() => setLoading(false)); }, [transactionUuid]);
  if (loading) return <main className="mx-auto max-w-4xl text-sm text-accent">Loading transaction…</main>;
  if (!record) return <main className="mx-auto max-w-4xl text-text"><p className="text-lg font-semibold text-text">Transaction not found</p><button type="button" onClick={() => router.push("/platform/transactions")} className="mt-5 text-sm text-accent">Back to transactions</button></main>;
  const { transaction, plan } = record; const statusIcon = transaction.status === "succeeded" ? <CheckCircle2 className="text-success" /> : transaction.status === "pending" ? <Clock3 className="text-warning" /> : <XCircle className="text-danger" />;
  const field = (label: string, value: string) => <div><p className="text-[10px] uppercase tracking-wider text-accent">{label}</p><p className="mt-1 break-all text-sm text-text">{value}</p></div>;
  const isTopup = plan?.plan_kind === "wallet_topup" || transaction.metadata?.planKind === "wallet_topup";
  return <main className="mx-auto max-w-4xl text-text"><button type="button" onClick={() => router.push("/platform/transactions")} className="flex items-center gap-2 text-sm text-accent hover:text-text"><ArrowLeft size={16} />Back to transactions</button><div className="mt-7 flex items-start justify-between"><div><p className="font-mono text-[11px] tracking-[.24em] text-accent">BILLING / TRANSACTION</p><h1 className="mt-3 text-3xl font-extrabold text-text">Transaction details</h1><p className="mt-2 text-sm text-muted">Complete payment and fulfillment record.</p></div><div className="flex items-center gap-2 rounded-full border border-brand-border bg-brand-soft px-3 py-2 text-xs text-text">{statusIcon}{transaction.status}</div></div><section className="mt-8 rounded-2xl border border-brand-border bg-brand-soft p-6"><div className="grid gap-6 sm:grid-cols-2">{field("Transaction ID", transaction.transaction_uuid)}{field("Plan / purpose", isTopup ? `${Number(transaction.metadata?.credits || 0).toLocaleString()} credit recharge` : plan?.name || "Plan removed")}{field("Type", isTopup ? "Wallet top-up" : "Service plan")}{field("Amount", `${(Number(transaction.amount_minor) / 100).toFixed(2)} ${transaction.currency}`)}{field("Payment method", transaction.payment_method)}{field("Created", new Date(transaction.created_at).toLocaleString())}{field("Stripe checkout session", transaction.stripe_checkout_session_id || "Not available")}{field("Stripe payment intent", transaction.stripe_payment_intent_id || "Not available")}</div>{plan && <div className="mt-8 border-t border-brand-border pt-6"><p className="text-xs uppercase tracking-wider text-accent">Plan details</p><div className="mt-4 grid gap-6 sm:grid-cols-2">{field("Credits granted", Number(plan.monthly_credits).toLocaleString())}{field("Billing interval", plan.billing_interval.replace("_", " "))}{field("Included services", Object.entries(plan.features || {}).filter(([, enabled]) => enabled).map(([key]) => key.toUpperCase()).join(" · ") || "Wallet credit only")}{field("Plan code", plan.code)}</div></div>}{isTopup && field("Credits granted", Number(transaction.metadata?.credits || 0).toLocaleString())}</section></main>;
}
